language: node_js
sudo: false
matrix:
  include:
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"
    - node_js: "7"
    - node_js: "8"
  fast_finish: true
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules


